### ISSUE TITLE
Hawkular - Shown as mutable

### ISSUE THREAD

**Issue by hhovsepy** [ManageIQ/manageiq-providers-hawkular#51]
In Hawkular Provider's summary page, the provider itself is not shown as immutable, the toolbar buttons (Power, Deployments, Driver, Datasources) are available, even though they fail to execute.
But these buttons should be hidden, as Hawkular provider is immutable.

Hawkular Agent is configured on Hawkular Server to be Immutable.

Please note that there is a issue with "Generate JDR" button, which should exist on Hawkular provider.
https://github.com/ManageIQ/manageiq-providers-hawkular/issues/50

![screenshot from 2017-09-19 12 43 00](https://user-images.githubusercontent.com/604313/30588735-2d06568a-9d38-11e7-9a8f-1d9a5102d830.png)

**Comment by abonas** [comment]
@cfcosta afaik it was fixed a while ago? is this a regression?

**Comment by cfcosta** [comment]
@hhovsepy 
I could not reproduce this, getting this screen (this screenshot is before the refresh, but the result is the same):

![](https://i.imgur.com/I0DioCm.png)

Am I doing anything wrong? The steps I did to try to replicate this bug:

* Dropped my db and started it over again (so old data does not interfere)
* Started an immutable hawkular by doing `hawkinit -a readme_data/hawkinit/immutable-agent.json`
* Added the provider as normal.
* Expected: power actions to be there. What happened: power buttons are not there.

I'm using latest master for both manageiq and manageiq-providers-hawkular.

**Comment by hhovsepy** [comment]
@cfcosta I still see the issue.
Go to Server's List -> Choose server Local (Hawkular) . And it is shown as mutable.

The standalone.xml configuration of Hawkular server is set as immutable:
<subsystem xmlns="urn:org.hawkular.agent:agent:1.0" auto-discovery-scan-period-secs="600" enabled="true" immutable="true" in-container="${hawkular.agent.in-container:false}" min-collection-interval-secs="${hawkular.agent.minCollectionIntervalSecs:30}">

**Comment by hhovsepy** [comment]
Closing the issue as it is coming from WildflyAgent which will be gone soon.
